version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building application...
      - zip -r lambda-package.zip ./*
  post_build:
    commands:
      - echo Deploying application...
      - aws lambda update-function-code --function-name shan_lambda_function --zip-file fileb://lambda-package.zip

artifacts:
  files:
    - lambda-package.zip
